### ISSUE TITLE
Unstaking amount issue

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3716] opened 2020-03-17 14:07 UTC

**Comment by Bitcoinera** [comment] 2020-03-17 16:09
Maybe we should close this as it solved "by itself" and we cannot reproduce it? 🤷‍♀

**Comment by Bitcoinera** [comment] 2020-03-17 19:26
Wasn't a bug but an user with an old Lunie version in cache

**Closed by Bitcoinera** 2020-03-17 19:26 UTC
