### ISSUE TITLE
KSM sending error - cannot initialize the API on mobile

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4631] opened 2020-07-30 20:35 UTC
User reports that they cannot send KSM funds and get the following error when they try. 

```createType(MultiSignature):: Unable to create Enum via index 104, in Ed25519, Sr25519, Ecdsa```

**Comment by jrmoreau** [comment] 2020-07-30 20:36
![ksmfail](https://user-images.githubusercontent.com/1614127/88971939-c6bbcf80-d282-11ea-9d86-39080fd1d1c6.png)

**Comment by Bitcoinera** [comment] 2020-07-31 11:40
But on the screenshot this looks like a different error

**Comment by Bitcoinera** [comment] 2020-07-31 12:16
I think these are two separate bugs. THe first one is from the extension and should be fixed here #4638

**Comment by Bitcoinera** [comment] 2020-07-31 12:32
Cannot reproduce the one from the screenshot:

<img width="410px" src="https://user-images.githubusercontent.com/40721795/89035059-8c156e00-d33a-11ea-9b6b-532c34c1a181.png">

**Comment by jrmoreau** [comment] 2020-07-31 19:06
@Bitcoinera user experienced both of these. not sure if/how they're related but anyhow, it's good the first one is fixed and should be merged soon

**Closed** 2020-08-11 15:23 UTC
