### ISSUE TITLE
withdrawing rewards doesn't update available balance until refresh

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3095] opened 2019-11-06 23:03 UTC
😞

**Comment by faboweb** [comment] 2019-11-26 13:57
Maybe dupe of #3183

**Comment by faboweb** [comment] 2019-11-29 08:06
works for me in prodcution

**Comment by jbibla** [comment] 2019-11-29 13:51
does not work for me in production or on mobile

**Comment by faboweb** [comment] 2019-11-29 15:15
just tested again...

**Comment by faboweb** [comment] 2019-11-29 15:16
hard referesh?

**Comment by jbibla** [comment] 2019-11-29 15:47
ok i believe you

**Comment by faboweb** [comment] 2019-12-02 10:52
@jbibla can you recheck? I just tested again and it works...

**Closed** 2019-12-03 15:24 UTC
Labels: bug :bug:
