### ISSUE TITLE
Error when performing any transaction on Kava - does not get sent to browser extension

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4772] opened 2020-08-27 02:08 UTC
User reported that any tx they try to do using Kava with their browser extension does not get sent to the extension. The modal shows the transaction (claiming, sending) waiting for the extension to confirm but nothing happens on the extension. 

Error shown below.

![photo_2020-08-26 21 57 15](https://user-images.githubusercontent.com/1614127/91374895-4045cf80-e7e7-11ea-975f-30f0d25607f8.jpeg)
![photo_2020-08-26 21 57 23](https://user-images.githubusercontent.com/1614127/91374897-40de6600-e7e7-11ea-9834-f6b3fcbe5798.jpeg)

**Comment by jrmoreau** [comment] 2020-08-27 02:10
Browser extension is the latest version

**Comment by faboweb** [comment] 2020-09-01 20:00
Can you ask for the address? I guess it is some funky account type. My query for transactionMetaData works fine

**Comment by jrmoreau** [comment] 2020-09-01 20:19
I will ask and share with you privately @faboweb

**Comment by Bitcoinera** [comment] 2020-09-04 12:00
@faboweb  are you then working on this?

**Comment by Bitcoinera** [comment] 2020-09-04 12:26
Mmm, I cannot reproduce, for me it is working as expected. On production, at least

<img width="340px" src="https://user-images.githubusercontent.com/40721795/92238971-858a9100-eeba-11ea-80bd-bfb075b43932.png">

**Comment by faboweb** [comment] 2020-09-05 16:44
I am still missing the failing asdress

**Comment by jrmoreau** [comment] 2020-09-06 13:22
@faboweb I don't have it. I've pinged user several times no response

**Comment by Bitcoinera** [comment] 2020-09-07 10:38
Probably because it's not an issue anymore. Should we close this?

**Comment by jrmoreau** [comment] 2020-09-08 13:52
@Bitcoinera please don't assume it's not an issue - we can close it if you want but I am not assuming it's resolved until it's confirmed.

**Comment by Bitcoinera** [comment] 2020-09-11 12:09
Has Sunny got back to you?

**Comment by jrmoreau** [comment] 2020-09-11 16:31
@Bitcoinera no - we can close it i suppose

**Closed** 2020-09-11 18:15 UTC
Labels: bug :bug:
