### ISSUE TITLE
e-Money eDKK unable to send with incorrect fee error message with Ledger Nano S

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#3965] opened 2020-05-04 15:47 UTC
**Describe the bug**
Trying to send eDKK to myself, no matter how little amount of eDKK I try to send myself the modal says I don't have enough to pay the fees, plus the fees cost shows as 0 in the final sending screen message.

![Screen Shot 2020-05-04 at 11 44 05 AM](https://user-images.githubusercontent.com/1614127/80985338-15c9a400-8dfd-11ea-9b00-7455acb11b08.png)

**Comment by faboweb** [comment] 2020-05-04 16:14
onchain applied fees @Bitcoinera ?

**Comment by Bitcoinera** [comment] 2020-05-04 16:36
e-Money doesn't have any. I had the same issue at the beginning and then it got fixed. Same for @jrmoreau it seems.

Will restart the app to check if I can reproduce

**Comment by Bitcoinera** [comment] 2020-05-04 16:42
Nope, cannot reproduce

**Comment by faboweb** [comment] 2020-05-04 16:55
@jrmoreau is this consistent?

**Comment by jrmoreau** [comment] 2020-05-04 19:18
@faboweb yes - I still cannot process the tx

**Comment by faboweb** [comment] 2020-05-04 19:47
On develop as well as production?

**Comment by faboweb** [comment] 2020-05-04 23:04
@jrmoreau you tested on mainnet? @Bitcoinera you tested on testnet?

**Comment by jrmoreau** [comment] 2020-05-04 23:39
I only tested in production on mainnet @faboweb

**Comment by faboweb** [comment] 2020-05-04 23:59
I remember we have a company mainnet account. @Bitcoinera maybe you can test with that?

**Comment by Bitcoinera** [comment] 2020-05-11 18:24
I have tried again following the very same steps and cannot reproduce this. Can you still @jrmoreau ?

**Comment by jrmoreau** [comment] 2020-05-11 22:09
I still cannot claim rewards or send edkk @Bitcoinera

**Comment by faboweb** [comment] 2020-05-11 23:08
Can you please work synchronous on this tomorrow

**Comment by jrmoreau** [comment] 2020-05-12 01:31
@faboweb what do you mean?

**Comment by Bitcoinera** [comment] 2020-05-12 09:26
We will! 👍

**Comment by Bitcoinera** [comment] 2020-05-13 16:55
OK, so @jrmoreau and I spent some time today debugging this and turns out, it is an UX problem!

The bug was simply that James had not enough balance to pay for the super high fees present on e-Money. So he was getting this error directly from the chain. It took us in fact a while to realize the problem is so simple: no money!

Maybe we can turn this issue to an UX issue or close this one and open a new one where to start the discussion on how to fix this for our users

**Comment by faboweb** [comment] 2020-05-13 18:37
But in the screenshot @jrmoreau shared the fees are 0. Are we not showing the chain applied fees? We should show the fees and prevent the user from proceeding.

**Comment by jrmoreau** [comment] 2020-05-13 18:46
Yes - preventing the user from proceeding would be helpful. Especially now that I cannot do anymore transactions with fees higher than .21 NGM 😬

**Comment by Bitcoinera** [comment] 2020-05-13 19:11
> Yes - preventing the user from proceeding would be helpful. Especially now that I cannot do anymore transactions with fees higher than .21 NGM 😬

Nice, this is an idea! Let's do this then. Only, I thought our plan was to leave the possibility for users to go and try to make a transaction even with 0 fee.

Only it seems this is not possible on e-Money and Terra.

So should we change the logic here and get rid of `adjustToMaxPayable`?

**Comment by faboweb** [comment] 2020-05-13 19:28
> So should we change the logic here and get rid of adjustToMaxPayable?

chain applied fees are not adjustable. So adjustToMaxPayable should not set those to 0.

**Comment by Bitcoinera** [comment] 2020-05-13 19:44
> chain applied fees are not adjustable. So adjustToMaxPayable should not set those to 0.

True. But in this case it wasn't a chainAppliedFee. Those are only on Terra.

The case here is that James had 0.19 available NGM on his balance. So then `adjustToMaxPayable` worked the way it was designed to and set the fee to the maximum he could pay, 0.19, overriding 0.55 that is our standard fee (I know, it is expensive, but this is how e-Money works).

So he went and tried to broadcast, getting the error 190700 ungm < 410000 ungm for fees or so

**Comment by Bitcoinera** [comment] 2020-05-13 19:45
@jrmoreau could you please upload a screenshot of this last error?

**Comment by jrmoreau** [comment] 2020-05-13 20:03
@Bitcoinera  I cannot reproduce because I have more NGM now, but the error text previously was

`Withdrawal failed: Broadcast was not successful: insufficient fees; got: "190071ungm" required: "291500echf,2035000edkk,275000eeur,3355000enok,3025000esek,550000ungm".
`

**Comment by Bitcoinera** [comment] 2020-05-13 20:08
Thank you so much James 🙏

**Comment by faboweb** [comment] 2020-05-13 22:11
ok so it's not chain applied fees. but for emoney it is like a minimum/exact fee to pay. maybe we can codify that logic somehow? maybe we return from the API a property `fixedFee` which turns of fee reduction in the UI. For now we can hard code this in the UI for emoney.

**Closed** 2020-05-15 17:12 UTC
Labels: bug :bug:
