### ISSUE TITLE
emoney currency selector is hidden on emoney-1 mainnet

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#3848] opened 2020-04-07 14:29 UTC
1. sign in with: emoney1cs4323dyzu0wxfj4vc62m8q3xsczfavqx9x3zd
2. currency selector is not present

**Comment by Bitcoinera** [comment] 2020-04-07 15:19
Yes, I found the issue. The issue is that we have a boolean, `isMultiDenomNetwork`, that turns true when the wallet has more balances apart from the `stakingDenom`.

Can be easily fixed by adding the `isMultiDenomNetwork` boolean directly to the network Object.

Or we could just enable fiat values for all networks (we'd just need to query current fiat values from coinmarketcap or so. Not very hard)

**Comment by faboweb** [comment] 2020-04-07 15:45
or remove `isMultiDenomNetwork` and assume all networks are multidenom. This also cleans the code

**Comment by faboweb** [comment] 2020-04-07 15:46
> Or we could just enable fiat values for all networks (we'd just need to query current fiat values from coinmarketcap or so. Not very hard)

will do, but let'S not do it now. most of the APIs cost a lot of money so we need to pick the right one.

**Comment by jbibla** [comment] 2020-04-07 17:58
> Or we could just enable fiat values for all networks (we'd just need to query current fiat values from coinmarketcap or so. Not very hard)

definitely would love to do this. it's on the company priority list!

**Closed** 2020-04-07 19:46 UTC
Labels: bug :bug:
