### ISSUE TITLE
Switching networks leaves data behind

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie#3129] opened 2019-11-13 17:25 UTC
**Describe the bug**

switching between networks leaves some data behind (testnet proposals appear in mainnet proposal list)

**To Reproduce**

Reporter was @jbibla 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by colw** [comment] 2019-11-14 17:49
Closed as cannot reproduce and the API returns correct proposals for network.

**Closed by colw** 2019-11-14 17:49 UTC
