### ISSUE TITLE
Cannot navigate to networks from the networks page

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie#4583] opened 2020-07-24 15:37 UTC
**Describe the bug**
When you are on the networks page and select a network to switch to the selector checkmark shows but it does not navigate you to the network. For example, if you click the gaia testnet for Cosmos, besides the network selector checkmark, nothing happens. There's no way to navigate to it. It seems the only direct way to navigate is using the browser extension.

![Screen Shot 2020-07-24 at 11 17 51 AM](https://user-images.githubusercontent.com/1614127/88408679-e4c89200-cda1-11ea-8c85-c66648353549.png)

**Comment by jbibla** [comment] 2020-07-24 18:33
oh my.

1. the sidebar is hidden on this page - not sure if that's intended (i kind of like it)
2. i can't reproduce the reported error - the switch happens as expected on my machine

can you check the console for errors?

**Comment by jrmoreau** [comment] 2020-07-24 18:39
@jbibla ignoring the intercom loading errors this is what I've seen:

`

  | eval | @ | vue-router.esm.js?4af9:2089
-- | -- | -- | --
  | abort | @ | vue-router.esm.js?4af9:2120
  | confirmTransition | @ | vue-router.esm.js?4af9:2128
  | transitionTo | @ | vue-router.esm.js?4af9:2072
  | push | @ | vue-router.esm.js?4af9:2403
  | eval | @ | vue-router.esm.js?4af9:2815
  | push | @ | vue-router.esm.js?4af9:2814
  | selectNetworkHandler | @ | NetworkList.vue?1462:59
  | click | @ | NetworkList.vue?d4ef:1
  | invokeWithErrorHandling | @ | vue.runtime.esm.js?e832:1854
  | invoker | @ | vue.runtime.esm.js?e832:2179
  | original._wrapper | @ | vue.runtime.esm.js?e832:6917
  | sentryWrapped | @ | helpers.js?aabc:71

`

**Comment by jrmoreau** [comment] 2020-07-24 18:40
```
vue-router.esm.js?4af9:2089 Uncaught (in promise) 
NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/cosmos-hub-testnet/validators") is not allowed", stack: "Error↵    at new NavigationDuplicated (webpack-int….sentryWrapped (webpack-internal:///4564:2938:23)"}
message: "Navigating to current location ("/cosmos-hub-testnet/validators") is not allowed"
name: "NavigationDuplicated"
_name: "NavigationDuplicated"
stack: "Error↵    at new NavigationDuplicated (webpack-internal:///4af9:1925:14)↵    at HTML5History.confirmTransition (webpack-internal:///4af9:2041:18)↵    at HTML5History.transitionTo (webpack-internal:///4af9:1985:8)↵    at HTML5History.push (webpack-internal:///4af9:2316:10)↵    at eval (webpack-internal:///4af9:2722:22)↵    at new Promise (<anonymous>)↵    at VueRouter.push (webpack-internal:///4af9:2721:12)↵    at VueComponent.selectNetworkHandler (webpack-internal:///97c7:213:57)↵    at click (webpack-internal:///97c7:3:383)↵    at invokeWithErrorHandling (webpack-internal:///e832:1701:26)↵    at HTMLLIElement.invoker (webpack-internal:///e832:1924:14)↵    at HTMLLIElement.original._wrapper (webpack-internal:///e832:6345:25)↵    at HTMLLIElement.sentryWrapped (webpack-internal:///4564:2938:23)"
__proto__: Error
```

**Comment by jbibla** [comment] 2020-07-24 18:42
perfect. thank you. ana fixed this here: https://github.com/luniehq/lunie/pull/4581

**Comment by jrmoreau** [comment] 2020-07-27 13:37
Thanks @jbibla closing

**Comment by jbibla** [comment] 2020-07-27 14:09
@jrmoreau is this resolved in production / can you reproduce?

**Comment by jrmoreau** [comment] 2020-07-27 14:16
@jbibla sidebar still disappears but the network switching works fine now. when you said `ana fixed this` I thought you meant to close it.

**Comment by jbibla** [comment] 2020-07-27 14:45
ok cool. if network switching works than we're good!

**Closed by jbibla** 2020-07-27 14:45 UTC
