### ISSUE TITLE
balances don't update after send tx on polkadot

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie#4742] opened 2020-08-18 19:14 UTC
**Describe the bug**

- send tx on polkadot - balances don't change
- also, using the extension - the action modal says the address is not present in the extension even though it is (and i completed a successful tx)

![Screen Shot 2020-08-18 at 3 07 18 PM](https://user-images.githubusercontent.com/6021933/90555521-79d26700-e165-11ea-8f2f-01b2223fcc3a.png)

**Comment by Bitcoinera** [comment] 2020-08-19 11:11
I cannot reproduce. Would suggest merging that PR and closing

<img width="540px" src="https://user-images.githubusercontent.com/40721795/90628159-6f73a400-e21d-11ea-86bf-347a39dc4387.png">

**Comment by Bitcoinera** [comment] 2020-08-19 11:13
But yeah, also without that PR it works. Still, the PR has a couple of important fixes

**Comment by Bitcoinera** [comment] 2020-08-19 15:36
I'd close this. None of us can reproduce

**Closed** 2020-08-19 19:28 UTC
Labels: bug :bug:
